# Generated by Django 2.2.1 on 2019-09-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='eamil',
            new_name='email',
        ),
    ]
