# Generated by Django 2.2.1 on 2019-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='goods_price',
            field=models.FloatField(default=10, verbose_name='商品单价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payorder',
            name='order_total',
            field=models.FloatField(verbose_name='订单总价'),
        ),
    ]
