# Generated by Django 2.2.1 on 2019-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='goods_delete',
            field=models.IntegerField(default=0),
        ),
    ]
