# Generated by Django 2.2.1 on 2019-09-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_cart_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='goods_delete',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_number',
        ),
    ]
