# Generated by Django 2.2.1 on 2019-09-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0003_auto_20190924_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Saller.LoginUser'),
        ),
    ]
